image:
  pullPolicy: Always

imagePullSecrets:
  - name: github

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 120

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 50m
    memory: 264Mi

livenessProbe:
  enabled: false
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 1

readinessProbe:
  enabled: false
  failureThreshold: 3
  httpGet:
    path: /
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 30
  successThreshold: 2

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "chatbot-site"

# configMap:
#   <VARIABLE>: <VARIABLE_VALUE>

# secrets:
#   <SECRET>: <BASE64_SECRET_VALUE>

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/proxy-connect-timeout: "240s"
    nginx.org/proxy-read-timeout: "240s"
    nginx.org/proxy-send-timeout: "240s"
    nginx.org/proxy-buffers: "8 16k"
    nginx.org/proxy-buffer-size: "16k"
    nginx.org/proxy-busy-buffers-size: "64k"
    nginx.org/websocket-services: "chatbot-site"
    nginx.org/location-snippets: |
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Credentials 'true' always;
      add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT' always;
      add_header Access-Control-Allow-Headers 'User-Agent,Keep-Alive,Content-Type' always;
      
      proxy_pass_header         Access-Control-Allow-Origin;
      proxy_pass_header         Access-Control-Allow-Credentials;
      proxy_pass_header         Access-Control-Allow-Methods;
      proxy_pass_header         Access-Control-Allow-Headers;
  hosts:
    - host: oec-chatbot-dev.datawheel.us
      paths:
        - /
        - /ws
  tls:
    - secretName: chatbot-site-ingress-tls
      hosts: 
        - oec-chatbot-dev.datawheel.us